"""
Django settings for MiddlewaresAndSessions project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zjm)ykqu)g7s2+_2*))v3gr6i-8y#ux+_i^7s0hm5edmd(08#3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

ALLOWED_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'MiddlewaresAndSessions.middlewares.SuspiciousActivityMiddleware',
    'MiddlewaresAndSessions.middlewares.IPWhitelistingMiddleware',
    'MiddlewaresAndSessions.middlewares.TotalRequestsCounter',
    'MiddlewaresAndSessions.middlewares.RequestLoggingMiddleware',
    'MiddlewaresAndSessions.middlewares.TrainingVersionMiddleware',
    'django.middleware.security.SecurityMiddleware',  # Adds basic protection and headers
    'django.contrib.sessions.middleware.SessionMiddleware',  # Handles django sessions logic
    'MiddlewaresAndSessions.middlewares.SessionRateLimitingMiddleware',
    'django.middleware.common.CommonMiddleware',  # Redirect if slash at the end of the url is missing
    'django.middleware.csrf.CsrfViewMiddleware',  # Enforces that we have a csrf token on post requests
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attaches the django user to the request
    'django.contrib.messages.middleware.MessageMiddleware',  # Handles django messages framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Prevents displaying our website in iframe
]

ROOT_URLCONF = 'MiddlewaresAndSessions.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MiddlewaresAndSessions.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SUPPORTED_LANGUAGES = {
    "en": "English",
    "de": "German",
    "bg": "Bulgarian",
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REQUESTS_PER_MINUTE = 5

SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True